spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evan
    username: root
    password: Database@19
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true